name: txt_class_4Lib
channels:
- conda-forge
- defaults
dependencies:
  - pip:
    - textract==1.5.0
  - python>=3.6
  - jupyter
  - nltk
  - numpy
  - pandas
  - matplotlib
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - lxml
